---
title: "preselected_check_baseline"
author: "Christopher D. Grady"
output: pdf_document
---

# Scan in data

```{r}
rm(list=ls())
pre <- read.csv("../preselected/preselected_participants_ID.csv")
sites <- read.csv("../site_respondent_selection/ECPN_sites_selected.csv")

base <- read.csv("../site_respondent_selection/12-21.csv")
base<- subset(base,base$consent_survey=="yes") #Remove no consent Surveys
base <- base[base$rct %in% 1,]
base <- droplevels(base)
# add names that enumerators wrote down on paper instead of putting into survey on day 1
base$num <- rownames(base)
base$num <- as.numeric(as.character(base$num))
base$name.1 <- as.character(base$name.1)
base$name.1[base$num %in% 2] <- "Suleiman"
base$name.1[base$num %in% 4] <- "Danjuma Okuwa"
base$name.1[base$num %in% 11] <- "Salisu"
base$name.1[base$num %in% 26] <- "Rukaya and Alwal"

# fix names in pre
pre$name[pre$name==""] <- NA 
pre$israel_name[pre$israel_name==""] <- NA
pre$name <- ifelse(is.na(pre$name), as.character(pre$israel_name), as.character(pre$name))

```

# match preNames with IDs from endline to remove ppl we didn't survey

```{r}
load("ecpn_endline.Rdata")
pre <- pre[pre$ID.Number %in% end$id_num,]
stopifnot(nrow(pre)==294)
rm(end)
```

# Match baseline names to preselected names

```{r}
# only need some cols
preNames <- pre[,c("name", "site_name")]
baseNames<-base[,c("name.1","site_num")]
sites <- sites[,c("site_num", "name")]

# need to merge site names and site numbers
preNames <- na.omit(data.frame(sapply(preNames, tolower))) # this will all be easier if everything is tolower
sites <- data.frame(sapply(sites, tolower))
baseNames <- data.frame(sapply(baseNames, tolower))

# spelling error and other peculiarities with site names
sites$name <- ifelse(sites$name == "ushatu", "ushata", as.character(sites$name))
preNames$site_name[preNames$site_name %in% "anyiin"] <- "anyii"
preNames$site_name[preNames$site_name %in% "zongo/daudu"] <- "zongo"
preNames$site_name[preNames$site_name %in% "sabon gida agan"] <- "sabon-gida agan"
preNames$site_name[preNames$site_name %in% "sabon gidan agan"] <- "sabon-gida agan"

#preNames has community names but it needs site_num
preNames$site_num <- sites$site_num[match(preNames$site_name, sites$name)]

# check that all names in preselected match exactly the names in baseline, and when they do not find those that do not.
preNames$name <- trimws(preNames$name) # found ws screwing things up
baseNames$name <- trimws(baseNames$name)
matches <- preNames[preNames$name %in% baseNames$name,]
test <- preNames[preNames$name %in% setdiff(preNames$name, baseNames$name),] # those that do not match
```

# Fuzzy Match the wrong names

```{r}
# also match on community
test$nameMatch <- paste0(test$name, "-", test$site_num)
baseNames$nameMatch <- paste0(baseNames$name, "-", baseNames$site_num)

# It creates a matrix with the Standard Levenshtein distance between the name fields of both sources
dist.name<-adist(test$nameMatch,baseNames$nameMatch, partial = TRUE, ignore.case = TRUE)
 
# We now take the pairs with the minimum distance
min.name<-apply(dist.name, 1, min)
 
matchNames<-NULL  
for(i in 1:nrow(dist.name))
{
    s2.i<-match(min.name[i],dist.name[i,])
    s1.i<-i
    matchNames<-rbind(data.frame(s2.i=s2.i,s1.i=s1.i,s2name=baseNames[s2.i,]$nameMatch, s1name=test[s1.i,]$nameMatch, adist=min.name[i]),matchNames)
}
# and we then can have a look at the results
#matchNames

# remove matches that are definitely not matches
matchNames <- matchNames[matchNames$adist <5,]
```


# add the correct names to the pre-selected df so it can be used to merge baseline/endline people.

```{r}
# make df of the matched names
matchNames2 <- matchNames[,c("s1name", "s2name")]
matchNames2[,c("s1name", "s2name")] <- cbind(sub("-[0-9]*","",matchNames2$s1name),sub("-[0-9]*","",matchNames2$s2name))
names(matchNames2) <- c("preName", "baseName") #s1name is preselected sheet, s2name is name from baseline

#chris: here
test <- merge(preNames, matchNames2, by.x="name", by.y="preName")

# and add fuzzy matched names to exact match "matches" df
matches$baseName <- matches$name
matches <- rbind(matches,test)

# add back in preselected number
pre$name <- trimws(tolower(pre$name))
matches$ID.Number <- pre$ID.Number[match(matches$name, pre$name)]
matches$ID.Number[matches$name %in% "adama ibrahim" & matches$site_name %in% "hunki"] <- 1238  # two people have same name, but live in diff places
stopifnot(table(matches$ID.Number)==table(pre$ID.Number))
```

# Save


```{r}
pre <- matches
save(pre, file="preselected_list.Rda")

```
