---
title: "make ICW indices"
author: "cdgrady21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
load("d-additiveIndices.Rdata")
library(dplyr)
library(estimatr)
library(psych)

# index functions
## icw
load(file="index_fun.rda")
# icwIndex function
```

# Separate into baseline and endline

```{r}
# first make rand.df to mess with
rand.df <- df

# then make var to indicate control group for ICW
rand.df$control <- ifelse(rand.df$treatment == 1, 0, 1)

# want separate baseline & endline indices
rand.df1 <- rand.df[rand.df$survey %in% 0,]
rand.df2 <- rand.df[rand.df$survey %in% 1,]

# removing panel people/preselected from endline, since not randomly selected
rand.df2 <- rand.df2[!rand.df2$pre_selected %in% 'pre',]

```

# Inverse Covariance Weighted Indices

Functions

```{r}
# both tr and co
ic.fun1 <- function(vars, thedf)
{
  x <- thedf[,vars]
  x <- zoo::na.aggregate(x)
  out_cw <- icwIndex(x)
  print(cor(x))
  print(out_cw$weights)
  return(as.vector(out_cw$index))
}


# just co
ic.fun <- function(vars, thedf)
{
  x <- thedf[,vars]
  x <- zoo::na.aggregate(x)
  out_cw <- icwIndex(xmat=x, sgroup=as.logical(thedf[,'control']))
  print(cor(x))
  print(out_cw$weights)
  return(as.vector(out_cw$index))
}
```

Doing.

```{r}
# should loop but feeling braindead
# Baseline
rand.df1$trust_cw <- ic.fun(trustVars, rand.df1)
rand.df1$dist_cw <- ic.fun(distVars, rand.df1)
rand.df1$attitude_cw <- ic.fun(attitudeVars, rand.df1)
rand.df1$x_cw <- ic.fun(xVars, rand.df1)
rand.df1$out_cw <- ic.fun(outVars, rand.df1)
rand.df1$other_cw <- ic.fun(otherVars, rand.df1)
#rand.df1$aware_cw <- ic.fun(awareVars, rand.df1) # just one variable
rand.df1$clash_cw <- ic.fun(clashVars, rand.df1)
rand.df1$contactOnly_cw <- ic.fun(contactVars[c(1:4,7)], rand.df1)
rand.df1$contactOnly_cats_cw <- ic.fun(paste0(contactVars[c(1:4,7)], "_cats"), rand.df1)
rand.df1$contactOnly_raw_cw <- ic.fun(paste0(contactVars[c(1:4,7)], "_raw"), rand.df1)
rand.df1$bene_cw <- ic.fun(beneVarsPerc, rand.df1)
rand.df1$threat_cw <- ic.fun(threatVars, rand.df1)
rand.df1$in_cw <- ic.fun(inVars, rand.df1)
rand.df1$cohes_cw <- ic.fun(cohesVars, rand.df1)
rand.df1$cohes1_cw <- ic.fun(cohesVars1, rand.df1)
rand.df1$cohes2_cw <- ic.fun(cohesVars2, rand.df1)
rand.df1$dis_cw <- ic.fun(disVars, rand.df1)
rand.df1$share_cw <- ic.fun(shareVars, rand.df1)
rand.df1$numDis_cw <- ic.fun(numDisVars, rand.df1)
rand.df1$resolve_cw <- ic.fun(resolveVars, rand.df1)
rand.df1$barg_cw <- ic.fun(bargVars, rand.df1)
rand.df1$disActor_cw <- ic.fun(disActorVars, rand.df1)
rand.df1$vio_cw <- ic.fun(vioVars, rand.df1)
rand.df1$vioExp_cw <- ic.fun(vioExpVars, rand.df1)
rand.df1$persp_cw <- rand.df1$persp_index
rand.df1$emp_cw <- ic.fun(empVars, rand.df1)
rand.df1$expand_cw <- ic.fun(expandVars, rand.df1)

# Endline
rand.df2$trust_cw <- ic.fun(trustVars, rand.df2)
rand.df2$dist_cw <- ic.fun(distVars, rand.df2)
rand.df2$attitude_cw <- ic.fun(attitudeVars, rand.df2)
rand.df2$x_cw <- ic.fun(xVars, rand.df2)
rand.df2$out_cw <- ic.fun(outVars, rand.df2)
rand.df2$other_cw <- ic.fun(otherVars, rand.df2)
#rand.df2$aware_cw <- ic.fun(awareVars, rand.df2) # only one var
rand.df2$clash_cw <- ic.fun(clashVars, rand.df2)
rand.df2$contactOnly_cw <- ic.fun(contactVars[c(1:4,7)], rand.df2)
rand.df2$contactOnly_cats_cw <- ic.fun(paste0(contactVars[c(1:4,7)], "_cats"), rand.df2)
rand.df2$contactOnly_raw_cw <- ic.fun(paste0(contactVars[c(1:4,7)], "_raw"), rand.df2)
rand.df2$bene_cw <- ic.fun(beneVarsPerc, rand.df2)
rand.df2$threat_cw <- ic.fun(threatVars, rand.df2)
rand.df2$in_cw <- ic.fun(inVars, rand.df2)
rand.df2$cohes_cw <- ic.fun(cohesVars, rand.df2)
rand.df2$cohes1_cw <- ic.fun(cohesVars1, rand.df2)
rand.df2$cohes2_cw <- ic.fun(cohesVars2, rand.df2)
rand.df2$dis_cw <- ic.fun(disVars, rand.df2)
rand.df2$share_cw <- ic.fun(shareVars, rand.df2)
rand.df2$numDis_cw <- ic.fun(numDisVars, rand.df2)
rand.df2$resolve_cw <- ic.fun(resolveVars, rand.df2)
rand.df2$barg_cw <- ic.fun(bargVars, rand.df2)
rand.df2$disActor_cw <- ic.fun(disActorVars, rand.df2)
rand.df2$vio_cw <- ic.fun(vioVars, rand.df2)
rand.df2$vioExp_cw <- ic.fun(vioExpVars, rand.df2)
rand.df2$persp_cw <- rand.df2$persp_index
rand.df2$emp_cw <- ic.fun(empVars, rand.df2)
rand.df2$expand_cw <- ic.fun(expandVars, rand.df2)

# Now scale as 0-1 so that we can easily discuss them as % increase/decrease for MC report. # not necessary until aggregated.
#icVars <- names(rand.df1)[grepl("_cw", names(rand.df1))]
#rand.df1[,icVars] <- reshape::rescaler(rand.df1[,icVars],type="range")
#rand.df2[,icVars] <- reshape::rescaler(rand.df2[,icVars],type="range")

# rebind
rand.df <- rbind(rand.df1, rand.df2)
```


# Rand Experiment

Needs to be done before aggregating.  Done in e-makeIndices_ap.Rmd file.



# Save

```{r}
save(rand.df, file="rand_df.Rdata")

```


